erDiagram
  CLASSIFICATION_TERM {
    string ENTERED_CLASSTERM  
    string CLASSTERM  
    string VALID_CLASSTERM  
    string INFRASPES_RANK  
    string INFRASPES_NAME  
    string SENSU_TERM  "s.str s.lat..."
  }
  NOTE {
    string NOTE_TEXT  "Note koblet til classification_event..."
  }
  HIERARCHICAL_PLACE {
    string HIERARCHICAL_PLACE_ID  "Søkefelt for å finne riktig hierchical_p..."
  }
  LOCALITY_PLACE {
    string LOCALITY  
  }
  ECOLOGY_PLACE {
    string ECOLOGY  
  }
  BIO_GEOGRAFISK_REGION {
    string BIO_GEO_REGION  
  }
  KOORDINATE_PLACE {
    string CA_UTM  
    string COORDINATE_ADDED_LATER  
    string DATUM  
    string ZONE  
    string BELT  
    string COORDINATE_STRING  
    string COORDINATE_EXPECTED_OUTPUT_ECHO  
    string PRECISION  
    string MAP_SHEET  
    string CA_ALTITUDE  
    string ALTITUDE_STRING  
    string ALTITUDE_EXPECTED_OUTPUT_ECHO  
    string CA_DEPTH  "Kun zoologi..."
    string DEPTH_STRING  "Kun zoologi..."
    string ACCURACY  
    string Ikkeibruk  "Ikke i bruk..."
  }
  EVENT_ROLE_PERSON_NAME {
    string PERSON_NAME_IDROLE_ID  "Kobling mellom Collecting event- og pers..."
    string ROLE_ID  "Navnet er utledet via håndskrift hvis ro..."
    string SORTING_SEQUENCE  "Hvilken rekkefølge skal samlerne vises i..."
    string PERSON_NAMEROLE_ID  "Se Leg..."
  }
  LEGNR {
    string MUSEUM_OBJECT_LEGNR_PERSON  "Kobling mellom object (belegg) og person..."
  }
  PERSON_NAME {
    string PERSON_NAME_ID  
    string TITLE  
    string PERSON_GIVEN_NAME  
    string PERSON_SURNAME  
  }
  ACTOR {
    string ACTOR_TYPE  
    string ACTORNAME  
    string GROUP_MEMBER_NAMES  
    string BIRTHDATE  
    string DEATHDATE  
    string ADRESS  
    string POSTAL_ADDRESS  
    string EMAIL_ADDRESS  
    string PHONE_NUMBER  
    string GENDER  
    string URL  
    string URL_NOTE  
    string NOTE  
  }
  OBJECT_ATTRIBUTES {
    string IS_REG  
    string IS_CORR  
    string IS_APPROVED  
    string OBJECT_WITHHELD  
    string REG_DATE  
    string KORR_DATE  
    string APPROVED_DATE  
    string LAST_MODIFIED  
    string REG_USER  
    string KORR_USER  
    string APPROVE_USER  
    string LAST_MODIFIED_BY  
    string IS_KORR  
  }
  DOCUMENT_OBJECT__REFERENCE_DOCUMENT {
    string DOCUMENT_REFERENCEDOCUMENT_TITLEDOCUMENT_TYPE  "DOCUMENT_OBJECT kobler REFERENCE_OBJECT ..."
  }
  EVENT_DOCUMENT__REFERENCE_DOCUMENT {
    string DOCUMENT_REFERENCEDOCUMENT_TITLEDOCUMENT_TYPE  "EVENT_DOCUMENT kobler REFERENCE_OBJECT t..."
  }
  TYPIFICATION_EVENT {
    string TYPIFICATION_TYPE_ID  "Holotype, Isotype,......."
  }
  PERSON_NAME_EVENT_ROLE {
    string PERSON_NAME_IDROLE_ID  "Kobling mellom typification_event og per..."
  }
  EVENT_DOCUMENT_REFERENCE_DOCUMENT {
    string DOCUMENT_REFERENCEDOCUMENT_TITLEDOCUMENT_TYPE  "EVENT_DOCUMENT kobler REFERENCE_OBJECT t..."
  }
  EVENT_NOTE__NOTE {
    string NOTE_TEXT  "Note koblet til TYPIFICATION_EVENT..."
  }
  TIMESPAN {
    string FROM_DATETO_DATE  "TIMESPAN koblet til TYPIFICATION_EVENT..."
  }