apiVersion: v1
kind: Pod
metadata:
  name: debug-pvc-explorer
  namespace: gbif-no-ns8095k
spec:
  containers:
  - name: debug
    image: busybox
    command: ["sleep", "3600"]
    volumeMounts:
    - name: data
      mountPath: /data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: 573890b9-3346-4027-ab0c-22eec6dfd665
