"""Bootstrap the Specify 7 Django ORM for use inside Prefect flows.

Adds the repo root and the ``specify7`` submodule to ``sys.path``,
generates the stub settings files Specify expects, patches SQLAlchemy
for version-2 compatibility, and calls ``django.setup()``.
"""

import os
import sys


def setup_django() -> None:
    """Idempotent Django bootstrap -- safe to call multiple times.

    Guards on Django's own ``apps.ready`` flag so retried Prefect tasks
    that call this again after a partial init don't hit the
    "populate() isn't reentrant" error.
    """
    from django.apps import apps
    if apps.ready:
        return

    try:
        import pymysql
        pymysql.install_as_MySQLdb()
    except ImportError:
        pass

    base_dir = os.path.dirname(  # repo root
        os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    )
    specify_dir = os.path.join(base_dir, "specify7")

    for path in (base_dir, specify_dir):
        if path not in sys.path:
            sys.path.append(path)

    _ensure_specify_settings(specify_dir)
    _patch_sqlalchemy_mapper()
    _patch_specify_cwd_open(specify_dir)

    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "specifyweb.settings")

    import django
    django.setup()


def _patch_specify_cwd_open(specify_dir: str) -> None:
    """Redirect Specify's CWD-relative ``open()`` calls to absolute paths.

    Upstream ``specify7`` opens a handful of JSON files with bare relative
    paths (e.g. ``open('specifyweb/backend/businessrules/uniqueness_rules.json')``).
    Those happen to work when the process CWD is the ``specify7`` directory
    (as in Docker / manage.py), but fail in Prefect workers whose CWD is the
    repo root.  We intercept those specific paths and resolve them against
    ``specify_dir`` so we don't have to modify the upstream submodule.
    """
    import builtins

    # Map each known bad relative path → absolute path within specify7/.
    _SPECIFY_RELATIVE_PATHS: dict[str, str] = {
        "specifyweb/backend/businessrules/uniqueness_rules.json": os.path.join(
            specify_dir,
            "specifyweb", "backend", "businessrules", "uniqueness_rules.json",
        ),
        "specifyweb/frontend/js_src/lib/components/DataModel/uniqueFields.json": os.path.join(
            specify_dir,
            "specifyweb", "frontend", "js_src", "lib", "components", "DataModel", "uniqueFields.json",
        ),
    }

    _real_open = builtins.open

    def _patched_open(file, *args, **kwargs):
        resolved = _SPECIFY_RELATIVE_PATHS.get(str(file))
        if resolved is not None:
            return _real_open(resolved, *args, **kwargs)
        return _real_open(file, *args, **kwargs)

    builtins.open = _patched_open  # type: ignore[assignment]


def _patch_sqlalchemy_mapper() -> None:
    """Shim ``sqlalchemy.orm.mapper`` for SQLAlchemy 2.x.

    Specify's ``stored_queries`` module calls the classical
    ``orm.mapper()`` API that was removed in SQLAlchemy 2.0.
    Prefect 3 requires SQLAlchemy 2, so we bridge the gap with
    ``registry.map_imperatively`` which has the same signature.
    """
    import sqlalchemy
    if not sqlalchemy.__version__.startswith("2"):
        return
    from sqlalchemy.orm import registry
    _registry = registry()
    sqlalchemy.orm.mapper = _registry.map_imperatively


_LOCAL_SPECIFY_SETTINGS = """\
# Auto-generated by flows/lib/specify_setup.py
# Reads the same DB_* env vars that the Helm secret-config provides.
import os

DATABASE_NAME = os.environ.get('DB_NAME', 'specify')
DATABASE_HOST = os.environ.get('DB_HOST', 'specify7-mariadb')
DATABASE_PORT = int(os.environ.get('DB_PORT', '3306'))

MASTER_NAME = os.environ.get('DB_USER', 'bn_specify')
MASTER_PASSWORD = os.environ.get('DB_PASSWORD', '')

APP_USER_NAME = MASTER_NAME
APP_USER_PASSWORD = MASTER_PASSWORD

SECRET_KEY = os.environ.get('SECRET_KEY', 'migration-worker-key')
WEB_ATTACHMENT_URL = os.environ.get('ASSET_SERVER_URL') or None
WEB_ATTACHMENT_KEY = os.environ.get('ATTACHMENT_KEY') or os.environ.get('ASSET_SERVER_KEY') or ''
WEB_ATTACHMENT_COLLECTION = os.environ.get('ASSET_SERVER_COLLECTION') or None

DEBUG = False
ALLOWED_HOSTS = ['*']
"""


def _ensure_specify_settings(specify_dir: str) -> None:
    """Create the Python files that Specify's settings/__init__.py expects.

    Mirrors what the Dockerfile and Helm secret-config.yaml produce:
      - build_version.py   (required import)
      - secret_key.py      (required import)
      - local_specify_settings.py  (DB connection + app settings)
    """
    settings_dir = os.path.join(specify_dir, "specifyweb", "settings")
    stubs = {
        "build_version.py": "VERSION = 'migration-worker'\n",
        "secret_key.py": "SECRET_KEY = 'migration-worker-key'\n",
        "local_specify_settings.py": _LOCAL_SPECIFY_SETTINGS,
    }
    for filename, content in stubs.items():
        path = os.path.join(settings_dir, filename)
        os.makedirs(settings_dir, exist_ok=True)
        if filename == "local_specify_settings.py" or not os.path.exists(path):
            with open(path, "w") as f:
                f.write(content)
