{{- if .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "specify7.fullname" . }}-backend-web
  labels:
    {{- include "specify7.labels" . | nindent 4 }}
    component: backend
spec:
  podSelector:
    matchLabels:
      {{- include "specify7.selectorLabels" . | nindent 6 }}
      component: backend
  policyTypes:
    - Ingress
  ingress:
    - from:
        {{- if .Values.networkPolicy.allowAllNamespaces }}
        - namespaceSelector: {}
        {{- else if .Values.networkPolicy.allowedNamespaceNames }}
        {{- range .Values.networkPolicy.allowedNamespaceNames }}
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ . | quote }}
        {{- end }}
        {{- else }}
        - podSelector: {}
        {{- end }}
      ports:
        - protocol: TCP
          port: 8000
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "specify7.fullname" . }}-static-web
  labels:
    {{- include "specify7.labels" . | nindent 4 }}
    component: static
spec:
  podSelector:
    matchLabels:
      {{- include "specify7.selectorLabels" . | nindent 6 }}
      component: static
  policyTypes:
    - Ingress
  ingress:
    - from:
        {{- if .Values.networkPolicy.allowAllNamespaces }}
        - namespaceSelector: {}
        {{- else if .Values.networkPolicy.allowedNamespaceNames }}
        {{- range .Values.networkPolicy.allowedNamespaceNames }}
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ . | quote }}
        {{- end }}
        {{- else }}
        - podSelector: {}
        {{- end }}
      ports:
        - protocol: TCP
          port: 80
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "specify7.fullname" . }}-asset-server-web
  labels:
    {{- include "specify7.labels" . | nindent 4 }}
    component: asset-server
spec:
  podSelector:
    matchLabels:
      {{- include "specify7.selectorLabels" . | nindent 6 }}
      component: asset-server
  policyTypes:
    - Ingress
  ingress:
    - from:
        {{- if .Values.networkPolicy.allowAllNamespaces }}
        - namespaceSelector: {}
        {{- else if .Values.networkPolicy.allowedNamespaceNames }}
        {{- range .Values.networkPolicy.allowedNamespaceNames }}
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ . | quote }}
        {{- end }}
        {{- else }}
        - podSelector: {}
        {{- end }}
      ports:
        - protocol: TCP
          port: 8080
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "specify7.fullname" . }}-asset-server-internal
  labels:
    {{- include "specify7.labels" . | nindent 4 }}
    component: asset-server
spec:
  podSelector:
    matchLabels:
      {{- include "specify7.selectorLabels" . | nindent 6 }}
      component: asset-server
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- include "specify7.selectorLabels" . | nindent 14 }}
              component: backend
        - podSelector:
            matchLabels:
              {{- include "specify7.selectorLabels" . | nindent 14 }}
              component: worker
      ports:
        - protocol: TCP
          port: 8080
{{- if not (eq .Values.reportRunner.enabled false) }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "specify7.fullname" . }}-report-runner-internal
  labels:
    {{- include "specify7.labels" . | nindent 4 }}
    component: report-runner
spec:
  podSelector:
    matchLabels:
      {{- include "specify7.selectorLabels" . | nindent 6 }}
      component: report-runner
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- include "specify7.selectorLabels" . | nindent 14 }}
              component: backend
      ports:
        - protocol: TCP
          port: 8080
{{- end }}
{{- if .Values.migrationHarness.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "specify7.fullname" . }}-migration-harness-web
  labels:
    {{- include "specify7.labels" . | nindent 4 }}
    component: migration-harness
spec:
  podSelector:
    matchLabels:
      {{- include "specify7.selectorLabels" . | nindent 6 }}
      component: migration-harness
  policyTypes:
    - Ingress
  ingress:
    - from:
        {{- if .Values.networkPolicy.allowAllNamespaces }}
        - namespaceSelector: {}
        {{- else if .Values.networkPolicy.allowedNamespaceNames }}
        {{- range .Values.networkPolicy.allowedNamespaceNames }}
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ . | quote }}
        {{- end }}
        {{- else }}
        - podSelector: {}
        {{- end }}
      ports:
        - protocol: TCP
          port: {{ .Values.migrationHarness.service.port }}
{{- end }}
{{- end }}
