{{- if and .Values.prefect.enabled .Values.prefect.worker.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "specify7.fullname" . }}-prefect-worker
  labels:
    {{- include "specify7.labels" . | nindent 4 }}
    component: prefect-worker
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create", "delete", "patch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "delete", "patch"]
{{- end }}
