{{- if not (eq .Values.reportRunner.enabled false) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "specify7.fullname" . }}-report-runner
  labels:
    {{- include "specify7.labels" . | nindent 4 }}
    component: report-runner
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.reportRunner.service.port | default 80 }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "specify7.selectorLabels" . | nindent 4 }}
    component: report-runner
{{- end }}
